repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: git@github.com:psf/black.git
    rev: 24.8.0
    hooks:
      - id: black

  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v1.11.2
    hooks:
      - id: mypy

  - repo: git@github.com:PyCQA/flake8.git
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: git@github.com:PyCQA/isort.git
    rev: 5.13.2
    hooks:
      - id: isort
